name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'src/**'
      - 'public/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Диагностика: убеждаемся, что запускается именно этот YAML
      - name: Show workflow file (debug)
        shell: bash
        run: |
          echo "== Repo workflows =="
          ls -la .github/workflows || true
          echo "== This file head =="
          sed -n '1,120p' .github/workflows/deploy-frontend.yml || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # УСТАНОВКА PNPM ЧЕРЕЗ NPM-GLOBAL + ЖЁСТКО ДОБАВЛЯЕМ В PATH
      - name: Install pnpm globally
        id: pnpm_install
        shell: bash
        run: |
          set -euo pipefail
          npm i -g pnpm@10.17.1
          PNPM_BIN="$(npm bin -g)"
          echo "PNPM_BIN=${PNPM_BIN}" >> "$GITHUB_OUTPUT"
          echo "$PNPM_BIN" >> "$GITHUB_PATH"

      # Проверяем, что pnpm действительно доступен (в отдельном шаге, т.к. $GITHUB_PATH работает со следующего шага)
      - name: Verify toolchain
        shell: bash
        run: |
          echo "PATH: $PATH"
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
          echo "PNPM which: $(which pnpm)"
          echo "PNPM ver: $(pnpm -v)"

      - name: Install dependencies (locked)
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_API_URL: https://api.technofame.store
        run: pnpm run build

      - name: Upload dist via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/**"
          target: "/home/${{ secrets.SSH_USER }}/frontend_upload"
          overwrite: true
          strip_components: 1

      - name: Atomic deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo -n /opt/deploy/deploy_frontend.sh
