name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'src/**'
      - 'public/**'
      - '.github/workflows/deploy-frontend.yml'

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # ВОТ ЗДЕСЬ PNPM, КАК ТЫ ХОТЕЛ
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
          run_install: false

      - name: Show tool versions
        run: |
          node -v
          pnpm -v
          which pnpm

      # Если у тебя есть pnpm-lock.yaml — можно вернуть --frozen-lockfile
      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build
        env:
          VITE_API_URL: https://api.technofame.store
        run: pnpm run build

      - name: Upload dist via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}     # deploy
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/**"
          target: "/home/${{ secrets.SSH_USER }}/frontend_upload"
          overwrite: true

      - name: Atomic deploy on server + health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}     # deploy
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            sudo -n /opt/deploy/deploy_frontend.sh
            code=$(curl -ks -o /dev/null -w "%{http_code}" https://technofame.store)
            case "$code" in
              200|301|302|304|308) echo "Frontend OK (HTTP $code)";;
              *) echo "Unexpected status: $code"; sudo systemctl status caddy --no-pager || true; sudo journalctl -u caddy -n 100 --no-pager || true; exit 1;;
            esac
