name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - 'tsconfig*.json'
      - 'src/**'
      - 'public/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # СНАЧАЛА ставим Node — этот шаг меняет PATH
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # ТЕПЕРЬ активируем pnpm — после setup-node, чтобы PATH не потерялся
      - name: Setup PNPM via Corepack
        shell: bash
        run: |
          set -euo pipefail
          corepack enable
          corepack prepare pnpm@10.17.1 --activate
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
          echo "PNPM: $(pnpm -v) via corepack"
          which pnpm || true

      # Короткий fallback: если по какой-то причине pnpm всё ещё не в PATH — ставим глобально
      - name: Ensure pnpm is available (fallback)
        if: ${{ success() }}
        shell: bash
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm not found after corepack — installing via npm -g…"
            npm i -g pnpm@10.17.1
          fi
          echo "PNPM final: $(pnpm -v)"
          which pnpm || true

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_API_URL: https://api.technofame.store
        run: pnpm run build

      - name: Upload dist via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}     # deploy
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/**"
          target: "/home/${{ secrets.SSH_USER }}/frontend_upload"
          overwrite: true
          strip_components: 1   # кладём содержимое dist прямо в frontend_upload/

      - name: Atomic deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}     # deploy
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo -n /opt/deploy/deploy_frontend.sh
