name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'vite.config.*'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Prepare .env.production
        run: |
          printf "VITE_API_URL=https://api.technofame.store\n" > .env.production

      - name: Build
        run: pnpm run build

      # Копируем сборку на сервер во временную директорию
      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "/tmp/frontend_dist_${{ github.sha }}/"
          strip_components: 1
          overwrite: true

      # Атомарно выкладываем в /var/www/frontend и перезагружаем Caddy
      - name: Publish on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            sudo apt-get update -y
            sudo apt-get install -y rsync
            sudo mkdir -p /var/www/frontend
            sudo rsync -a --delete "/tmp/frontend_dist_${{ github.sha }}/" /var/www/frontend/
            sudo chown -R www-data:www-data /var/www/frontend
            sudo systemctl reload caddy
